export type PrimitiveTokenName =
  | "border.style.solid"
  | "border.width.none"
  | "border.width.strong"
  | "border.width.thin"
  | "color.blue.600"
  | "color.blue.700"
  | "color.palette.accent"
  | "color.palette.accent.hover"
  | "color.palette.backdrop"
  | "color.palette.border"
  | "color.palette.canvas"
  | "color.palette.dark.accent"
  | "color.palette.dark.accent.hover"
  | "color.palette.dark.backdrop"
  | "color.palette.dark.border"
  | "color.palette.dark.canvas"
  | "color.palette.dark.invalid"
  | "color.palette.dark.invalid.hover"
  | "color.palette.dark.muted"
  | "color.palette.dark.surface.elevated"
  | "color.palette.graphite"
  | "color.neutral.0"
  | "color.neutral.50"
  | "color.neutral.200"
  | "color.neutral.400"
  | "color.neutral.600"
  | "color.neutral.900"
  | "color.neutral.900.translucent"
  | "color.red.700"
  | "color.palette.invalid.hover"
  | "color.palette.muted"
  | "color.palette.primary"
  | "color.palette.surface"
  | "font.family.mono"
  | "font.family.sans"
  | "font.size.2xl"
  | "font.size.lg"
  | "font.size.md"
  | "font.size.sm"
  | "font.size.xl"
  | "font.size.xs"
  | "font.weight.bold"
  | "font.weight.medium"
  | "font.weight.regular"
  | "font.weight.semibold"
  | "letter.spacing.normal"
  | "letter.spacing.tight"
  | "line.height.body"
  | "line.height.relaxed"
  | "line.height.tight"
  | "motion.duration.fast"
  | "motion.duration.slow"
  | "radius.full"
  | "radius.lg"
  | "radius.md"
  | "radius.square"
  | "radius.sm"
  | "size.content.prose"
  | "size.content.wide"
  | "size.control.lg"
  | "size.control.md"
  | "size.control.sm"
  | "size.layout.item.lg"
  | "size.layout.item.md"
  | "size.layout.item.sm"
  | "space.0"
  | "space.1"
  | "space.2"
  | "space.3"
  | "space.4"
  | "space.6"
  | "space.8"
  | "space.12"
  | "space.16"
  | "z.index.100"
  | "z.index.200"
  | "z.index.300";

export type SemanticTokenName =
  | "border.style"
  | "border.width"
  | "border.width.strong"
  | "color.accent"
  | "color.accent.foreground"
  | "color.accent.hover"
  | "color.border"
  | "color.backdrop"
  | "color.canvas"
  | "color.focus"
  | "color.invalid"
  | "color.invalid.foreground"
  | "color.invalid.hover"
  | "color.link"
  | "color.primary"
  | "color.primary.foreground"
  | "color.primary.hover"
  | "color.surface"
  | "color.surface.elevated"
  | "color.text"
  | "color.text.muted"
  | "font.family.body"
  | "font.family.code"
  | "font.size.body"
  | "font.size.heading.lg"
  | "font.size.heading.md"
  | "font.size.heading.sm"
  | "font.size.small"
  | "font.weight.body"
  | "font.weight.emphasis"
  | "letter.spacing.heading"
  | "line.height.body"
  | "line.height.heading"
  | "motion.duration.fast"
  | "motion.duration.slow"
  | "radius"
  | "radius.button"
  | "radius.card"
  | "radius.checkbox"
  | "radius.circle"
  | "radius.control"
  | "radius.overlay"
  | "radius.pill"
  | "radius.surface"
  | "size.content.prose"
  | "size.content.wide"
  | "size.control.lg"
  | "size.control.md"
  | "size.control.sm"
  | "size.layout.item.lg"
  | "size.layout.item.md"
  | "size.layout.item.sm"
  | "space.0"
  | "space.1"
  | "space.2"
  | "space.3"
  | "space.4"
  | "space.6"
  | "space.8"
  | "space.12"
  | "space.16"
  | "z.index.modal"
  | "z.index.overlay"
  | "z.index.toast";

export type TokenValues<Name extends string> = Readonly<Record<Name, string>>;

export type ThemeName = "dark" | "light";

export type SemanticTokenReferences = Readonly<
  Record<SemanticTokenName, PrimitiveTokenName>
>;

export interface ThemeTokenContract {
  readonly semanticReferences: SemanticTokenReferences;
  readonly semantic: TokenValues<SemanticTokenName>;
}

export interface MetriqTokenContract {
  readonly name: "metriq";
  readonly primitives: TokenValues<PrimitiveTokenName>;
  /** The light-theme aliases retained for compatibility with the 1.0 contract. */
  readonly semanticReferences: SemanticTokenReferences;
  readonly semantic: TokenValues<SemanticTokenName>;
}

export interface ThemeAwareMetriqTokenContract extends MetriqTokenContract {
  readonly themes: Readonly<Record<ThemeName, ThemeTokenContract>>;
}
